insert into teams(teamLocation,teamMascot,teamAbbr,league,division )
values ('Pittsburgh','Pirates','PIT','NL','Central'),
('Texas','Rangers','TEX','AL','West'),
('Kansas City','Royals','KC','AL','Central'),
('Colorado','Rockies','COL','NL','West'),
('St. Louis','Cardinals','STL','NL','Central'),
('Minnesota','Twins','MIN','AL','Central'),
('Chicago','Cubs','CHC','NL','Central'),
('Tampa Bay','Rays','TB','AL','East'),
('Seattle','Mariners','SEA','AL','West'),
('Boston','Red Sox','BOS','AL','East'), 
('OaklAND','Athletics','OAK','AL','West'),
('Milwaukee','Brewers','MIL','NL','Central'),
('Miami','Marlins','MIA','NL','East'),
('ClevelAND','Indians','CLE','AL','Central'),
('San Francisco','Giants','SF','NL','West'),
('Toronto','Blue Jays','TOR','AL','East'),
('Los Angeles','Angels','LAA','AL','West'),
('Atlanta','Braves','ATL','NL','East'),
('Washington','Nationals','WSH','NL','East'),
('Houston','Astros','HOU','AL','West'),
('New York','Mets','NYM','NL','East'),
('Cincinnati','Reds','CIN','NL','Central'),
('Detroit','Tigers','DET','AL','Central'),
('Baltimore','Orioles','BAL','AL','East'),
('New York','Yankees','NYY','AL','East'),
('San Diego','Padres','SD','NL','West');

insert into players(teamID, firstName, lastName, position ,throws, hits )
values
((SELECT teamID FROM teams WHERE teamAbbr = 'PIT'),"Chris","Archer","SP","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'PIT'),"Josh","Bell","1B","R","B"),
((SELECT teamID FROM teams WHERE teamAbbr = 'PIT'),"Francisco","Liriano","SP","L","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'PIT'),"Starling","Marte","CF","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'PIT'),"Colin","Moran","3B","R","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'PIT'),"Kevin","Newman","SS","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'PIT'),"Gregory","Polanco","RF","L","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'PIT'),"Bryan","Reynolds","LF","R","B"),
((SELECT teamID FROM teams WHERE teamAbbr = 'PIT'),"Jacob","Stallings","C","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'PIT'),"Cole","Tucker","SS","R","B"),
((SELECT teamID FROM teams WHERE teamAbbr = 'PIT'),"Felipe","Vazquez","RP","L","L"),

((SELECT teamID FROM teams WHERE teamAbbr = 'TEX'), "Elvis","ANDrus","SS","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'TEX'),"Asdrubal","Cabrera","3B","R","B"),
((SELECT teamID FROM teams WHERE teamAbbr = 'TEX'), "Jesse","Chavez","RP","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'TEX'), "Delino","DeShields","LF","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'TEX'), "Ronald","Guzman","1B","L","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'TEX'),"Ariel","Jurado","RP","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'TEX'), "Shawn","Kelley","RP","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'TEX'), "Isiah","Kiner-Falefa","C","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'TEX'), "Chris","Martin","RP","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'TEX'), "Nomar","Mazara","RF","L","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'TEX'), "Rougned","Odor","2B","R","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'TEX'), "Hunter","Pence","RF","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'TEX'), "Danny","Santana","CF","R","B"),

((SELECT teamID FROM teams WHERE teamAbbr = 'KC'), "Scott","Barlow","RP","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'KC'), "Cheslor","Cuthbert","3B","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'KC'), "Danny","Duffy","SP","L","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'KC'), "Brian","Flynn","RP","L","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'KC'), "Cam","Gallagher","C","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'KC'), "Alex","Gordon","LF","R","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'KC'), "Billy","Hamilton","CF","R","B"),
((SELECT teamID FROM teams WHERE teamAbbr = 'KC'), "Nicky","Lopez","2B","R","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'KC'), "Kevin","McCarthy","RP","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'KC'), "Whit","Merrifield","2B","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'KC'), "Adalberto","Mondesi","2B","R","B"),
((SELECT teamID FROM teams WHERE teamAbbr = 'KC'), "Ryan","O\'Hearn","1B","L","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'KC'), "Jorge","Soler","RF","R","R"),

((SELECT teamID FROM teams WHERE teamAbbr = 'COL'), "Nolan","Arenado","3B","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'COL'), "David","Dahl","LF","R","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'COL'), "Ian","Desmond","1B","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'COL'), "Jairo","Diaz","RP","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'COL'), "Chris","Iannetta","C","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'COL'), "Peter","Lambert","SP","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'COL'), "Scott","Oberg","RP","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'COL'), "Mark","Reynolds","1B","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'COL'), "Brendan","Rodgers","SS","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'COL'), "Trevor","Story","SS","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'COL'), "Raimel","Tapia","CF","L","L"),

((SELECT teamID FROM teams WHERE teamAbbr = 'STL'), "Harrison","Bader","CF","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'STL'), "Matt","Carpenter","1B","R","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'STL'), "Paul","DeJong","SS","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'STL'), "Dexter","Fowler","RF","R","B"),
((SELECT teamID FROM teams WHERE teamAbbr = 'STL'), "John","Gant","RP","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'STL'), "Paul","Goldschmidt","1B","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'STL'), "Jordan","Hicks","RP","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'STL'), "Dakota","Hudson","SP","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'STL'), "ANDrew","Miller","RP","L","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'STL'), "Marcell","Ozuna","LF","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'STL'), "Matt","Wieters","C","R","B"),
((SELECT teamID FROM teams WHERE teamAbbr = 'STL'), "Kolten","Wong","2B","R","L"),

((SELECT teamID FROM teams WHERE teamAbbr = 'MIN'), "Ehire","Adrianza","SS","R","B"),
((SELECT teamID FROM teams WHERE teamAbbr = 'MIN'), "Willians","Astudillo","C","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'MIN'), "Jose","Berrios","SP","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'MIN'), "C.J.","Cron","1B","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'MIN'), "Mitch","Garver","C","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'MIN'), "Marwin","Gonzalez","3B","R","B"),
((SELECT teamID FROM teams WHERE teamAbbr = 'MIN'), "Max","Kepler","RF","L","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'MIN'), "Matt","Magill","RP","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'MIN'), "Trevor","May","RP","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'MIN'), "Jorge","Polanco","SS","R","B"),
((SELECT teamID FROM teams WHERE teamAbbr = 'MIN'), "Taylor","Rogers","RP","L","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'MIN'), "Eddie","Rosario","LF","R","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'MIN'), "Jonathan","Schoop","2B","R","R"),

((SELECT teamID FROM teams WHERE teamAbbr = 'CHC'), "Albert","Almora Jr.","CF","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'CHC'), "Javier","Baez","SS","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'CHC'), "David","Bote","3B","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'CHC'), "Kris","Bryant","3B","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'CHC'), "Willson","Contreras","C","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'CHC'), "Daniel","Descalso","3B","R","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'CHC'), "Carl","Edwards Jr.","RP","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'CHC'), "Jose","Quintana","SP","L","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'CHC'), "Anthony","Rizzo","1B","L","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'CHC'), "Kyle","Ryan","SP","L","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'CHC'), "Kyle","Schwarber","LF","R","L"),

((SELECT teamID FROM teams WHERE teamAbbr = 'TB'), "Willy","Adames","SS","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'TB'), "Christian","Arroyo","3B","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'TB'), "Jalen","Beeks","RP","L","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'TB'), "Diego","Castillo","RP","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'TB'), "Travis","d'Arnaud","C","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'TB'), "YANDy","Diaz","3B","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'TB'), "Avisail","Garcia","RF","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'TB'), "Kevin","Kiermaier","CF","R","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'TB'), "Austin","Meadows","CF","L","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'TB'), "Tommy","Pham","CF","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'TB'), "Daniel","Robertson","2B","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'TB'), "Chaz","Roe","RP","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'TB'), "Ryne","Stanek","RP","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'TB'), "Hunter","Wood","RP","R","R"),

((SELECT teamID FROM teams WHERE teamAbbr = 'SEA'), "Austin","Adams","RP","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'SEA'), "Anthony","Bass","RP","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'SEA'), "Gerson","Bautista","RP","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'SEA'), "BrANDon","Brennan","RP","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'SEA'), "Roenis","Elias","SP","L","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'SEA'), "Edwin","Encarnacion","DH","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'SEA'), "Matt","Festa","RP","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'SEA'), "Cory","Gearrin","RP","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'SEA'), "Mitch","Haniger","RF","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'SEA'), "Shed","Long","2B","R","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'SEA'), "Tommy","Milone","SP","L","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'SEA'), "Dylan","Moore","3B","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'SEA'), "Omar","Narvaez","C","R","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'SEA'), "Domingo","Santana","RF","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'SEA'), "Kyle","Seager","3B","R","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'SEA'), "Mallex","Smith","CF","R","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'SEA'), "Daniel","Vogelbach","1B","R","L"),

((SELECT teamID FROM teams WHERE teamAbbr = 'BOS'), "Matt","Barnes","RP","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'BOS'), "ANDrew","Benintendi","LF","L","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'BOS'), "Mookie","Betts","RF","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'BOS'), "XANDer","Bogaerts","SS","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'BOS'), "Jackie","Bradley Jr.","CF","R","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'BOS'), "Ryan","Brasier","RP","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'BOS'), "Colten","Brewer","RP","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'BOS'), "Michael","Chavis","3B","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'BOS'), "Rafael","Devers","3B","R","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'BOS'), "Heath","Hembree","RP","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'BOS'), "J.D.","Martinez","LF","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'BOS'), "Eduardo","Nunez","2B","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'BOS'), "Josh","Taylor","RP","L","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'BOS'), "Christian","Vazquez","C","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'BOS'), "Marcus","Walden","RP","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'BOS'), "Ryan","Weber","RP","R","R"),

((SELECT teamID FROM teams WHERE teamAbbr = 'OAK'), "Ryan","Buchter","RP","L","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'OAK'), "Mark","Canha","1B","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'OAK'), "Matt","Chapman","3B","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'OAK'), "Khris","Davis","LF","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'OAK'), "Mike","Fiers","SP","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'OAK'), "Liam","Hendriks","RP","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'OAK'), "Ramon","Laureano","CF","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'OAK'), "Josh","Phegley","C","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'OAK'), "Chad","Pinder","SS","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'OAK'), "Stephen","Piscotty","RF","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'OAK'), "Jurickson","Profar","SS","R","B"),
((SELECT teamID FROM teams WHERE teamAbbr = 'OAK'), "Marcus","Semien","SS","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'OAK'), "Joakim","Soria","RP","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'OAK'), "Lou","Trivino","RP","R","R"),

((SELECT teamID FROM teams WHERE teamAbbr = 'MIL'), "Jesus","Aguilar","1B","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'MIL'), "OrlANDo","Arcia","SS","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'MIL'), "Ryan","Braun","LF","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'MIL'), "Lorenzo","Cain","CF","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'MIL'), "Josh","Hader","RP","L","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'MIL'), "Jeremy","Jeffress","RP","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'MIL'), "Mike","Moustakas","2B","R","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'MIL'), "Freddy","Peralta","SP","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'MIL'), "Hernan","Perez","3B","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'MIL'), "Manny","Pina","C","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'MIL'), "Christian","Yelich","RF","R","L"),

((SELECT teamID FROM teams WHERE teamAbbr = 'MIA'), "Jorge","Alfaro","C","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'MIA'), "Brian","ANDerson","3B","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'MIA'), "Austin","Brice","RP","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'MIA'), "Starlin","Castro","2B","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'MIA'), "Garrett","Cooper","LF","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'MIA'), "Austin","Dean","LF","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'MIA'), "Tayron","Guerrero","RP","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'MIA'), "Harold","Ramirez","RF","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'MIA'), "JT","Riddle","SS","R","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'MIA'), "Miguel","Rojas","SS","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'MIA'), "Sergio","Romo","SP","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'MIA'), "Caleb","Smith","SP","L","R"),

((SELECT teamID FROM teams WHERE teamAbbr = 'CLE'), "Trevor","Bauer","SP","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'CLE'), "Jake","Bauers","LF","L","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'CLE'), "Jon","Edwards","RP","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'CLE'), "Jason","Kipnis","2B","R","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'CLE'), "Francisco","Lindor","SS","R","B"),
((SELECT teamID FROM teams WHERE teamAbbr = 'CLE'), "Jordan","Luplow","RF","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'CLE'), "Leonys","Martin","CF","R","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'CLE'), "Tyler","Naquin","CF","R","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'CLE'), "Roberto","Perez","C","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'CLE'), "Jose","Ramirez","2B","R","B"),
((SELECT teamID FROM teams WHERE teamAbbr = 'CLE'), "Carlos","Santana","1B","R","B"),
((SELECT teamID FROM teams WHERE teamAbbr = 'CLE'), "Josh","Smith","RP","L","L"),

((SELECT teamID FROM teams WHERE teamAbbr = 'SF'), "Shaun","ANDerson","SP","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'SF'), "BrANDon","Belt","1B","L","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'SF'), "BrANDon","Crawford","SS","R","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'SF'), "Steven","Duggar","CF","R","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'SF'), "Mark","Melancon","RP","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'SF'), "Reyes","Moronta","RP","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'SF'), "Joe","Panik","2B","R","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'SF'), "Kevin","Pillar","CF","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'SF'), "Pablo","SANDoval","3B","R","B"),
((SELECT teamID FROM teams WHERE teamAbbr = 'SF'), "Stephen","Vogt","C","R","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'SF'), "Tony","Watson","RP","L","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'SF'), "Mike","Yastrzemski","LF","L","L"),

((SELECT teamID FROM teams WHERE teamAbbr = 'TOR'), "BrANDon","Drury","3B","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'TOR'), "Freddy","Galvis","SS","R","B"),
((SELECT teamID FROM teams WHERE teamAbbr = 'TOR'), "RANDal","Grichuk","LF","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'TOR'), "Vladimir","Guerrero Jr.","3B","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'TOR'), "Lourdes","Gurriel Jr.","2B","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'TOR'), "Teoscar","HernANDez","RF","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'TOR'), "Edwin","Jackson","SP","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'TOR'), "Elvis","Luciano","RP","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'TOR'), "Luke","Maile","C","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'TOR'), "Tim","Mayza","RP","L","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'TOR'), "Thomas","Pannone","RP","L","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'TOR'), "Justin","Smoak","1B","L","B"),
((SELECT teamID FROM teams WHERE teamAbbr = 'TOR'), "Eric","Sogard","2B","R","L"),

((SELECT teamID FROM teams WHERE teamAbbr = 'LAA'), "Jaime","Barria","SP","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'LAA'), "Kole","Calhoun","RF","L","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'LAA'), "David","Fletcher","SS","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'LAA'), "Dustin","Garneau","C","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'LAA'), "Brian","Goodwin","CF","R","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'LAA'), "Tommy","La Stella","3B","R","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'LAA'), "Shohei","Ohtani","DH","R","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'LAA'), "Luis","Rengifo","2B","R","B"),
((SELECT teamID FROM teams WHERE teamAbbr = 'LAA'), "Tyler","Skaggs","SP","L","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'LAA'), "Mike","Trout","CF","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'LAA'), "Jared","Walsh","1B","L","L"),

((SELECT teamID FROM teams WHERE teamAbbr = 'ATL'), "Ronald","Acuna Jr.","LF","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'ATL'), "Ozzie","Albies","2B","R","B"),
((SELECT teamID FROM teams WHERE teamAbbr = 'ATL'), "Josh","Donaldson","3B","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'ATL'), "Mike","Foltynewicz","SP","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'ATL'), "Freddie","Freeman","1B","R","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'ATL'), "Nick","Markakis","RF","L","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'ATL'), "Brian","McCann","C","R","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'ATL'), "Sean","Newcomb","SP","L","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'ATL'), "Austin","Riley","3B","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'ATL'), "Dansby","Swanson","SS","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'ATL'), "Jacob","Webb","RP","R","R"),

((SELECT teamID FROM teams WHERE teamAbbr = 'WSH'), "Patrick","Corbin","SP","L","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'WSH'), "Brian","Dozier","2B","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'WSH'), "Yan","Gomes","C","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'WSH'), "Matt","Grace","RP","L","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'WSH'), "Javy","Guerra","RP","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'WSH'), "Howie","Kendrick","2B","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'WSH'), "Anthony","Rendon","3B","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'WSH'), "Victor","Robles","CF","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'WSH'), "Tony","Sipp","RP","L","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'WSH'), "Juan","Soto","LF","L","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'WSH'), "Michael","Taylor","CF","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'WSH'), "Trea","Turner","SS","R","R"),

((SELECT teamID FROM teams WHERE teamAbbr = 'HOU'), "Michael","Brantley","LF","L","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'HOU'), "Alex","Bregman","3B","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'HOU'), "Robinson","Chirinos","C","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'HOU'), "Chris","Devenski","RP","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'HOU'), "Derek","Fisher","CF","R","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'HOU'), "Yuli","Gurriel","1B","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'HOU'), "Will","Harris","RP","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'HOU'), "Josh","James","SP","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'HOU'), "Tony","Kemp","LF","R","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'HOU'), "Jake","Marisnick","CF","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'HOU'), "Jack","Mayfield","2B","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'HOU'), "Roberto","Osuna","RP","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'HOU'), "Ryan","Pressly","RP","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'HOU'), "Hector","Rondon","RP","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'HOU'), "Justin","VerlANDer","SP","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'HOU'), "Tyler","White","2B","R","R"),

((SELECT teamID FROM teams WHERE teamAbbr = 'NYM'), "Pete","Alonso","1B","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'NYM'), "Michael","Conforto","RF","R","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'NYM'), "Jeurys","Familia","RP","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'NYM'), "Todd","Frazier","3B","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'NYM'), "Adeiny","Hechavarria","SS","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'NYM'), "Juan","Lagares","CF","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'NYM'), "Seth","Lugo","SP","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'NYM'), "Tomas","Nido","C","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'NYM'), "Amed","Rosario","SS","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'NYM'), "Dominic","Smith","1B","L","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'NYM'), "Zack","Wheeler","SP","R","L"),

((SELECT teamID FROM teams WHERE teamAbbr = 'CIN'), "Tucker","Barnhart","C","R","B"),
((SELECT teamID FROM teams WHERE teamAbbr = 'CIN'), "Anthony","DeSclafani","SP","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'CIN'), "Derek","Dietrich","LF","R","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'CIN'), "Amir","Garrett","RP","L","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'CIN'), "Jose","Iglesias","SS","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'CIN'), "Michael","Lorenzen","RP","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'CIN'), "WANDy","Peralta","RP","L","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'CIN'), "Yasiel","Puig","RF","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'CIN'), "Nick","Senzel","3B","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'CIN'), "Eugenio","Suarez","3B","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'CIN'), "Joey","Votto","1B","R","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'CIN'), "Jesse","Winker","RF","L","L"),

((SELECT teamID FROM teams WHERE teamAbbr = 'DET'), "Austin","Adams","RP","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'DET'), "Victor","Alcantara","RP","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'DET'), "Gordon","Beckham","3B","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'DET'), "Nicholas","Castellanos","RF","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'DET'), "BrANDon","Dixon","LF","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'DET'), "Buck","Farmer","RP","R","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'DET'), "Niko","Goodrum","SS","R","B"),
((SELECT teamID FROM teams WHERE teamAbbr = 'DET'), "Grayson","Greiner","C","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'DET'), "JaCoby","Jones","LF","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'DET'), "Dawel","Lugo","2B","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'DET'), "Daniel","Norris","SP","L","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'DET'), "Ronny","Rodriguez","3B","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'DET'), "Christin","Stewart","LF","R","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'DET'), "Daniel","Stumpf","RP","L","L"),

((SELECT teamID FROM teams WHERE teamAbbr = 'BAL'), "Hanser","Alberto","SS","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'BAL'), "Miguel","Castro","RP","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'BAL'), "Chris","Davis","1B","R","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'BAL'), "David","Hess","RP","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'BAL'), "Trey","Mancini","LF","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'BAL'), "Richie","Martin","SS","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'BAL'), "Renato","Nunez","3B","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'BAL'), "Rio","Ruiz","3B","R","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'BAL'), "Chance","Sisco","C","R","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'BAL'), "Dwight","Smith Jr.","RF","R","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'BAL'), "Stevie","Wilkerson","SS","R","B"),

((SELECT teamID FROM teams WHERE teamAbbr = 'NYY'), "Aroldis","Chapman","RP","L","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'NYY'), "Thairo","Estrada","SS","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'NYY'), "Clint","Frazier","LF","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'NYY'), "Chad","Green","RP","R","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'NYY'), "J.A.","Happ","SP","L","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'NYY'), "Aaron","Hicks","CF","R","B"),
((SELECT teamID FROM teams WHERE teamAbbr = 'NYY'), "DJ","LeMahieu","2B","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'NYY'), "Cameron","Maybin","LF","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'NYY'), "Kendrys","Morales","DH","R","B"),
((SELECT teamID FROM teams WHERE teamAbbr = 'NYY'), "Gary","Sanchez","C","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'NYY'), "Gio","Urshela","3B","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'NYY'), "Luke","Voit","1B","R","R"),

((SELECT teamID FROM teams WHERE teamAbbr = 'SD'), "Austin","Hedges","C","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'SD'), "Ian","Kinsler","2B","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'SD'), "Joey","Lucchesi","SP","L","L"),
((SELECT teamID FROM teams WHERE teamAbbr = 'SD'), "Manny","Machado","SS","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'SD'), "Manuel","Margot","CF","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'SD'), "Wil","Myers","RF","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'SD'), "Hunter","Renfroe","RF","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'SD'), "Franmil","Reyes","CF","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'SD'), "Craig","Stammen","RP","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'SD'), "FernANDo","Tatis Jr.","SS","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'SD'), "Trey","Wingenter","RP","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'SD'), "Matt","Wisler","SP","R","R"),
((SELECT teamID FROM teams WHERE teamAbbr = 'SD'), "Kirby","Yates","RP","R","L");


insert into games(startTime ,homeTeam ,awayTeam ,homeScore ,awayScore )
values


('2019-06-06 20:05:00', (SELECT teamID FROM teams WHERE teamAbbr = 'TEX'),(SELECT teamID FROM teams WHERE teamAbbr =  'BAL'), 4, 3),
('2019-06-06 13:15:00', (SELECT teamID FROM teams WHERE teamAbbr = 'KC'),(SELECT teamID FROM teams WHERE teamAbbr =  'BOS'),5, 7),
('2019-06-06 14:20:00', (SELECT teamID FROM teams WHERE teamAbbr = 'CHC'),(SELECT teamID FROM teams WHERE teamAbbr =  'COL'), 1, 3),
('2019-06-06 13:15:00', (SELECT teamID FROM teams WHERE teamAbbr = 'STL'),(SELECT teamID FROM teams WHERE teamAbbr =  'CIN'), 3, 1),
('2019-06-06 19:00:00', (SELECT teamID FROM teams WHERE teamAbbr = 'CLE'),(SELECT teamID FROM teams WHERE teamAbbr =  'MIN'), 4, 5),
('2019-06-06 22:07:00', (SELECT teamID FROM teams WHERE teamAbbr = 'LAA'),(SELECT teamID FROM teams WHERE teamAbbr =  'OAK'), 4, 7),
('2019-06-06 14:10:00', (SELECT teamID FROM teams WHERE teamAbbr = 'MIL'),(SELECT teamID FROM teams WHERE teamAbbr =  'MIA'), 5, 1),
('2019-06-06 12:10:00', (SELECT teamID FROM teams WHERE teamAbbr = 'NYM'),(SELECT teamID FROM teams WHERE teamAbbr =  'SF'), 7, 3),
('2019-06-06 19:00:00', (SELECT teamID FROM teams WHERE teamAbbr = 'TOR'),(SELECT teamID FROM teams WHERE teamAbbr =  'NYY'), 2, 6),
('2019-06-06 12:35:00', (SELECT teamID FROM teams WHERE teamAbbr = 'PIT'),(SELECT teamID FROM teams WHERE teamAbbr =  'ATL'), 6, 1),
('2019-06-06 22:10:00', (SELECT teamID FROM teams WHERE teamAbbr = 'SD'),(SELECT teamID FROM teams WHERE teamAbbr =  'WSH'), 5, 4),
('2019-06-06 15:40:00', (SELECT teamID FROM teams WHERE teamAbbr = 'SEA'),(SELECT teamID FROM teams WHERE teamAbbr =  'HOU'), 7, 8),
('2019-06-06 13:10:00', (SELECT teamID FROM teams WHERE teamAbbr = 'DET'),(SELECT teamID FROM teams WHERE teamAbbr =  'TB'), 1, 6);

insert into hitterStats (playerID, gameID, teamID, atBats,runs ,hits ,doubles ,triples ,homeRuns ,runsBattedIn ,walks ,strikeOut ,steals )
values
  ((SELECT playerID FROM players WHERE firstName = 'Josh' AND lastName = 'Bell' AND position = '1B'), (SELECT gameID FROM games WHERE startTime = '2019-06-06 12:35:00' AND homeTeam = (SELECT teamID FROM teams WHERE teamAbbr = 'PIT') AND awayTeam = (SELECT teamID FROM teams WHERE teamAbbr = 'ATL')), (SELECT teamID FROM teams WHERE teamAbbr = 'PIT'),4, 2, 3, 3, 0, 0, 2, 0, 0, 0),
  ((SELECT playerID FROM players WHERE firstName = 'Starling' AND lastName = 'Marte' AND position = 'CF'), (SELECT gameID FROM games WHERE startTime = '2019-06-06 12:35:00' AND homeTeam = (SELECT teamID FROM teams WHERE teamAbbr = 'PIT') AND awayTeam = (SELECT teamID FROM teams WHERE teamAbbr = 'ATL')), (SELECT teamID FROM teams WHERE teamAbbr = 'PIT'),4, 0, 0, 0, 0, 0, 0, 0, 0, 0),
  ((SELECT playerID FROM players WHERE firstName = 'Colin' AND lastName = 'Moran' AND position = '3B'), (SELECT gameID FROM games WHERE startTime = '2019-06-06 12:35:00' AND homeTeam = (SELECT teamID FROM teams WHERE teamAbbr = 'PIT') AND awayTeam= (SELECT teamID FROM teams WHERE teamAbbr = 'ATL')), (SELECT teamID FROM teams WHERE teamAbbr = 'PIT'),3, 1, 1, 0, 0, 1, 2, 0, 1, 0),
  ((SELECT playerID FROM players WHERE firstName = 'Kevin' AND lastName = 'Newman' AND position = 'SS'), (SELECT gameID  FROM games WHERE startTime = '2019-06-06 12:35:00' AND homeTeam = (SELECT teamID FROM teams WHERE teamAbbr = 'PIT') AND awayTeam = (SELECT teamID FROM teams WHERE teamAbbr = 'ATL')), (SELECT teamID FROM teams WHERE teamAbbr = 'PIT'),4, 0, 0, 0, 0, 0, 0, 0, 1, 0);

insert into pitcherStats(playerID, gameID, teamID, wins, innerPitched, hits, runs, earnedRuns, strikeOuts, walks)

values 
((SELECT playerID FROM players WHERE firstName ='Chris'	AND lastName = 'Archer'	AND position = 'SP'),	(SELECT gameID FROM games WHERE startTime = '2019-06-06 12:35:00' AND homeTeam = (SELECT teamID FROM teams WHERE teamAbbr = 'PIT') AND awayTeam = (SELECT teamID FROM teams WHERE teamAbbr = 'ATL')), (SELECT teamID FROM teams WHERE teamAbbr = 'PIT'),	1,	6,	6,	1,	1,	2,	6),
((SELECT playerID FROM players WHERE firstName ='Francisco'	AND lastName = 'Liriano' AND position = 'SP'),		(SELECT gameID FROM games WHERE startTime = '2019-06-06 12:35:00' AND homeTeam = (SELECT teamID FROM teams WHERE teamAbbr = 'PIT') AND awayTeam = (SELECT teamID FROM teams WHERE teamAbbr = 'ATL')), (SELECT teamID FROM teams WHERE teamAbbr = 'PIT'),	1,	1.2,	0,	0,	0,	0,	1),
((SELECT playerID FROM players WHERE firstName ='Felipe'	AND lastName = 'Vazquez'  AND position = 'RP'),	(SELECT gameID FROM games WHERE startTime = '2019-06-06 12:35:00' AND homeTeam = (SELECT teamID FROM teams WHERE teamAbbr = 'PIT') AND awayTeam = (SELECT teamID FROM teams WHERE teamAbbr = 'ATL')), (SELECT teamID FROM teams WHERE teamAbbr = 'PIT')	,1, 1.1	,1, 0, 0, 2, 1), 
((SELECT playerID FROM players WHERE firstName ='Jesse'	AND lastName = 'Chavez'	  AND position = 'RP'),	(SELECT gameID FROM games WHERE startTime = '2019-06-06 20:05:00' AND homeTeam = (SELECT teamID FROM teams WHERE teamAbbr = 'TEX')	AND awayTeam = (SELECT teamID FROM teams WHERE teamAbbr = 'BAL')), (SELECT teamID FROM teams WHERE teamAbbr = 'TEX') ,1, 1	,0, 0, 0, 0, 1);
